### ISSUE TITLE
impirium just... doesn't?

### ISSUE THREAD

**Issue by gdi-1** [Bawnorton/Impirium#4]
### No other mods installed

Every time I boot the game, I get this error:
Uncaught exception in thread "main"
```
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:400)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:310)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:110)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:627)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:611)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:563)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:540)
	at com.bawnorton.impirium.ImPIriumAgent.<clinit>(ImPIriumAgent.java:39)
	... 8 more
```
And, I have no idea why this is happening either. If anyone has any tips to get the mod running, please reply to this issue with them.

**Comment by Bawnorton** [comment]
In order to use Impirium you need a JDK and not a JRE. You're probably using modrinth which uses a JRE unlike most other launchers, including vanillas.

**Comment by gdi-1** [comment]
Thanks for that! I didn't know that different launchers can affect how mods work like that.
